# The length of the hash used to identify a parameter combination
hash_length: 7

# If true, use Singularity instead of Docker
# Singularity support is only available on Unix
singularity: false

algorithms:
  - name: "omicsintegrator1"
    params:
      include: true
      run1:
        b: [2]
        w: [.5]
        d: [10]
        mu: [0]
  - name: "omicsintegrator2"
    params:
      include: true
      run1:
        b: [4]
        g: [0]

datasets:
  - label: alopecia_areata
    data_dir: datasets/diseases
    edge_files:
      - raw/string_interactome.txt
    node_files:
      - prize_files/alopecia_areata_prizes.txt
    other_files: []
  - label: diabetes_mellitus
    data_dir: datasets/diseases
    edge_files:
      - raw/string_interactome.txt
    node_files:
      - prize_files/diabetes_mellitus_prizes.txt
    other_files: []

reconstruction_settings:
  locations:
    reconstruction_dir: output/diseases
  run: true
analysis:
  graphspace:
    include: false
  cytoscape:
    include: false
  summary:
    include: true
  ml:
    include: false
  evaluation:
    include: true

gold_standards:
  - # Labels can only contain letters, numbers, or underscores
    label: gs0
    node_files: ['GS_files/Alopecia_areata_GS.txt']
    # edge_files: [] TODO: later iteration
    data_dir: "datasets/diseases"
    # List of dataset labels to compare with the specific gold standard dataset
    dataset_labels: ["alopecia_areata"]

  - # Labels can only contain letters, numbers, or underscores
    label: gs1
    node_files: ['GS_files/Diabetes_mellitus_GS.txt']
    # edge_files: [] TODO: later iteration
    data_dir: "datasets/diseases"
    # List of dataset labels to compare with the specific gold standard dataset
    dataset_labels: ["diabetes_mellitus"]

